name: CI

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v4

      - name: Build
        run: cargo build
        working-directory: ./src-tauri

      - name: Test
        run: cargo test
        working-directory: ./src-tauri
